### ISSUE TITLE
[BUG] Vehicles Don't Spawn on Used Car Lot When Sold by Owner

### ISSUE THREAD

**Issue by lildiznick** [qbcore-framework/qb-vehiclesales#15]
I've recently run into an issue where players attempt to sale a car on the used car lot, but when they sell it, it doesn't spawn on the lot and disappears from their owned vehicle list.  I have all the latest commits of every  qb script as they've been released in the #fivem-changelog channel of the Discord.  There are no client or console errors.  and oxmysql is version 1.4.1

**Comment by shehanwijeyaweera** [comment]
same thing happened to me after adding more custom vehicles.

**Comment by lildiznick** [comment]
The add on cars may be the issue.  I've added quite a few and that's when the issue started for me.  But not until I had more than like 4 or 5 IRL add on cars.  They're added in the shared.lua and the vehicle shop in the config so they spawn in there
