### ISSUE TITLE
Attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by ArtysV** [qbcore-framework/qb-vehiclesales#40]
![image](https://user-images.githubusercontent.com/98827458/161232716-aaab2a44-61f7-4c85-b33b-565843b53c17.png)

After fresh installation I've got this error

**Comment by Belorico** [comment]
I have it too

**Comment by txdaniel55** [comment]
Same issue with clean install

**Comment by QBLes** [comment]
please refer to https://github.com/qbcore-framework/qb-vehiclesales/issues/44#issuecomment-1097509775 see if this fixes your issue.

Regards,
Les
