### ISSUE TITLE
attempting to index a nil value (field '?')

### ISSUE THREAD

**Issue by xlGaM3r** [qbcore-framework/qb-vehiclesales#44]
So The Script is completely working but i have trouble with Import cars "Custom Cars"

SCRIPT ERROR: @qb-vehiclesales/client/main.lua:355: attempt to index a nil value (field '?')
handler(5@qb-vehiclesales/client/main.lua:355)
fn(@qb-vehiclesales/client/main.lua:153)

**Comment by xlGaM3r** [comment]
FYI Cars Work Perfect in a QB-Garages

**Comment by QBLes** [comment]
My guess is you guys are using another Garage script, if you look in your qb-garage script go in client.lua look for 

qb-garage:server:checkVehicleOwner

under this look for the cb(true)

change this to cb(treu, result[1].balance)


Regards,
Les.

**Comment by Maureks** [comment]
@QBLes I'am using fresh, qb-garages from the qb-core framework

**Comment by Maureks** [comment]
yeah , just as I thought , it already comes with it : 
![image](https://user-images.githubusercontent.com/84512488/163190785-35f42b38-ee2c-46e0-8d28-d42fdf9f5eb3.png)

**Comment by QBLes** [comment]
> yeah , just as I thought , it already comes with it : ![image](https://user-images.githubusercontent.com/84512488/163190785-35f42b38-ee2c-46e0-8d28-d42fdf9f5eb3.png)

yeah this was just something i come accross yesterday helping people that used a diff qb-garages script thought could be the same problem.

**Comment by Maureks** [comment]
Thanks @QBLes for trying at least !

**Comment by QBLes** [comment]
> Thanks @QBLes for trying at least !

if you have time feel free to join qb support chat on the discord someone will be happy to try and help you.

**Comment by Maureks** [comment]
my problem seemed to be the polyzone , it works fine now

**Comment by SrPeterr** [comment]
> my problem seemed to be a bad configurated polyzone , it works fine now

Hi! Could you show me how you fixed it? 😅
