### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tamer173** [qbcore-framework/qb-vehiclesales#52]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
I added a vehicle for sale when i logged in back after restarting my server i got the error i added the screenshot below

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/105336574/182787043-393babc4-582a-4c6c-900f-2e125962d481.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by sinphoenix** [comment]
Are you still having this issue?

**Comment by sinphoenix** [comment]
Could not replicate issue. Tested multiple times using different models.

**Comment by Tamer173** [comment]
No it got fixed thanks
