### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dk1122** [qbcore-framework/qb-vehiclesales#54]
![Screenshot 2022-08-07 200925](https://user-images.githubusercontent.com/97806363/183296879-5ebebf1e-e7fa-4b41-8864-b492413b67be.jpg)

**Comment by Dk1122** [comment]
after adding new garage

**Comment by CptNoHand** [comment]
I have the same

**Comment by BillyWong73** [comment]
I am having the same issue, has there been a fix? Mine is just from trying to sale a car to the used dealer i haven't added any garages yet.

![Screenshot 2022-08-15 205912](https://user-images.githubusercontent.com/111316844/184767720-12a7afad-f926-481f-b77a-019ce81aa748.png)
.

**Comment by i-kulgu** [comment]
Can you guys download the latest version and try it again ?
I can't find a comparison on line 313.

**Comment by CptNoHand** [comment]
> 

Yes, its line 321 now, berfore the newest merge it was 313.

            if balance < 1 then

**Comment by i-kulgu** [comment]
> > 
> 
> Yes, its line 321 now, berfore the newest merge it was 313.
> 
> ```
>         if balance < 1 then
> ```

Are you using the default qb-garage or a different one ?

**Comment by CptNoHand** [comment]
I'm using the default one. Everything is updated aswell.

**Comment by CptNoHand** [comment]
who do you mean? i still have it

**Comment by sinphoenix** [comment]
have you redownloaded and tried since we updated it?

**Comment by Dk1122** [comment]
Update new qb-core then fix it

**Comment by CptNoHand** [comment]
> Update new qb-core then fix it 

I updated everything and still have the issue.

**Comment by sinphoenix** [comment]
let me see if i can try and get the issue to happen on my end!

**Comment by sinphoenix** [comment]
i can not get this issue to pop on my end.

**Comment by D4isDAVID** [comment]
I'm thinking that the error is in the database, most likely some script didn't save the vehicle correctly. Try checking all the vehicles in the database and that they have a `balance` value

**Comment by CptNoHand** [comment]
We don't use qb-vehicleshop, could that be the problem? Cause if so, that's a bit meh.

**Comment by D4isDAVID** [comment]
If the resource that you use doesn't save the vehicle correctly in the database, then it's the problem.

**Comment by CptNoHand** [comment]
The ones we tried are spawned via Adminmenu

**Comment by GhzGarage** [comment]
This resource has a check for a balance because the vehicle shop has financing and we weren’t going to let people go to this shop and sell immediately after financing. There’s nothing “meh” about it

**Comment by CptNoHand** [comment]
> This resource has a check for a balance because the vehicle shop has financing and we weren’t going to let people go to this shop and sell immediately after financing. There’s nothing “meh” about it

Which makes sense. That meh wasn't against the code, but for the fact i have to look into it for our server, as we don't use qb-vehicleshop. 

Good to know what the problem is. Thanks guys.

**Comment by CptNoHand** [comment]
> I am having the same issue, has there been a fix? Mine is just from trying to sale a car to the used dealer i haven't added any garages yet.
> 
> ![Screenshot 2022-08-15 205912](https://user-images.githubusercontent.com/111316844/184767720-12a7afad-f926-481f-b77a-019ce81aa748.png) .

If you still have it, i have changed the code in my fork, you just have to delete the balance check, if you don't use qb-vehicleshop
