### ISSUE TITLE
[BUG] Vehicle duplication after selling

### ISSUE THREAD

**Issue by davoucci** [qbcore-framework/qb-vehiclesales#60]
**Describe the bug**
When I sell the vehicle to a citizen, the vehicle is duplicated and I am able to drive it even if the vehicle no longer belongs to me. I would like the vehicle to disappear instead.

**To Reproduce**
1. Go to vehicule sale
2. Click on sell vehicle
4. Now look at the duplication (even if the vehicle ain't yours anymore, still an duplication)

**Expected behavior**
I want to see the vehicle disappear totally when i sold it to an other citizen.

**Comment by sinphoenix** [comment]
are you using the newest version of the script itself? i tried to reproduce this and can not

**Comment by sinphoenix** [comment]
No response for several days. We will be closing this bug. If you are still having this issue please create another ticket!

**Comment by Fresnowolf** [comment]
im having this issue after buying the car despawns
