### ISSUE TITLE
[BUG] Same Vehicles Shown In All Zones

### ISSUE THREAD

**Issue by IIP1AX** [qbcore-framework/qb-vehiclesales#61]
**Describe the bug**
if i add new Config.Zones like another place to sell your vehicle.. it will show the same vehicles that's already placed in for sale in the SandyOccasions

**To Reproduce**
1. Go to 'Config.lua'
2. 'add new Config.Zone'
3. then but your car for sale in the new zone or in SandyOccasions 
4. see the same vehicle in both zones

**Expected behavior**
Determine the name of the Zone in the data base in which the vehicle is for sale

**Screenshots**
![image](https://user-images.githubusercontent.com/104531548/189616398-3315f264-939a-487f-8d19-049e666a85fe.png)
![image](https://user-images.githubusercontent.com/104531548/189616403-71342f10-800f-4a18-8b7a-0b331e495337.png)
![image](https://user-images.githubusercontent.com/104531548/189616390-6b8bfdd0-2a6e-483e-8990-82dc97b82e94.png)

**Questions (please complete the following information):**
 - When you last updated: [Today]
 - Are you using custom resource? which ones? [no]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
nothing

**Comment by sinphoenix** [comment]
Is this still an issue?

**Comment by 0411447** [comment]
I'm having the same issue, really annoying tbh cause it's a good srcipt

**Comment by 0411447** [comment]
> I was able to reproduce this error and I'm going to work on fixing this today. Thank you for the information

Any joy with a fix?

**Comment by 0411447** [comment]
Still no fix yet?

**Comment by IIP1AX** [comment]
yeah still not fix...
