### ISSUE TITLE
[BUG] I have a new qb-garages I Cant't sell  how can I fix it plz

### ISSUE THREAD

**Issue by AmineBissane** [qbcore-framework/qb-vehiclesales#68]
![image](https://user-images.githubusercontent.com/122304331/212426856-70e90d51-fa82-4eec-9b8e-26950a16b619.png)

**Comment by joshinator-Josh** [comment]
same here im having the same issue whe i go to sell the vehicle

**Comment by DNDdjay** [comment]
try too add this in ur database


ALTER TABLE `player_vehicles`
ADD COLUMN `balance` int(11) NOT NULL DEFAULT 0;

**Comment by KaineNorth** [comment]
> try too add this in ur database
> 
> ALTER TABLE `player_vehicles` ADD COLUMN `balance` int(11) NOT NULL DEFAULT 0;

Thank you very very much!

**Comment by F0xzY** [comment]
> try too add this in ur database
> 
> ALTER TABLE `player_vehicles` ADD COLUMN `balance` int(11) NOT NULL DEFAULT 0;

Can you send a pic of how your sql file looks?
