### ISSUE TITLE
qb-vehiclesales

### ISSUE THREAD

**Issue by Mario-LaRusso** [qbcore-framework/qb-vehiclesales#73]
Describe the bug
I have changed the coords along with the polyzone in another location but now I get this error can someone help me please?  
he doesn't want to put the car up for sale and the like

To Reproduce

Go to 'Config.lua'
1 polyzone put in coords in it
2 spawn locations Etc Put in

Expected behavior

That We Can Move The qb-vehiclesales Easier
   
![image](https://user-images.githubusercontent.com/104788666/224486195-be38f3d4-e102-44e1-a069-be7d0f45fe24.png)
![image](https://user-images.githubusercontent.com/104788666/224486222-581779d4-3135-4eea-8f31-6ed0a4bf46c4.png)
![image](https://user-images.githubusercontent.com/104788666/224486240-dd3a186a-b39a-4a43-b09a-15a188530516.png)
![image](https://user-images.githubusercontent.com/104788666/224486251-55ff391b-768b-4de4-bc6c-52c97ca89ca1.png)
![image](https://user-images.githubusercontent.com/104788666/224486300-034b79a7-3fbe-4eb4-b3e3-183b3215a4d9.png)

**Comment by lMikki** [comment]
I got the same error, did you fix it?

**Comment by masutto** [comment]
i have the same error as well
